
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "../../(main)/global.css";
import Sidebar from "../../../Components/dashboard/sidebar";
import Footer from "../../../Components/dashboard/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-inter", 
});
export const dynamic = "force-dynamic";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await getMessages(locale);
  console.log(locale);


  return (
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className="flex h-full grow">
            <Sidebar />
            {children}
          </div>
            <Footer/>
        </NextIntlClientProvider>
  );
}
