import { Inter } from "next/font/google";
import { getMessages } from "next-intl/server";
import "./global.css";
import Header from "../../Components/header";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-inter", // 👈 هتستخدمه في Tailwind كـ CSS variable
});
export const dynamic = "force-dynamic";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await getMessages(locale);
  console.log(locale);

  return (
    <>
      <Header />
      {children}
    </>
  );
}
