import { Inter } from "next/font/google";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import "./(main)/global.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'react-hot-toast';
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-inter",
});
export const dynamic = "force-dynamic";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await getMessages(locale);
  console.log(locale);

  return (
    <ClerkProvider>
        <NextIntlClientProvider locale={locale} messages={messages}>
        <html
          lang={locale}
          dir={locale === "ar" ? "rtl" : "ltr"}
          className={inter.className}
        >
          <head>
            <link
              href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&amp;display=swap"
              rel="stylesheet"
            />
            <link
              href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
              rel="stylesheet"
            />
          </head>
          <body className="bg-background-light dark:bg-[#131c26] font-display text-text-light dark:text-text-dark">
            <Toaster position="bottom-center" /> 
            {children}
          </body>
        </html>
    </NextIntlClientProvider>
      </ClerkProvider>
  );
}
